server:
  port: 2226

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: inputSubscriber
      default:
        contentType: application/json
