server:
  port: 2225

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
      bindings:
        output:
          destination: outputSubscriber
          group: outputSubscriberGroup
        input:
          destination: inputSubscriber
          group: inputSubscriberGroup